jsrpg.random._arrayNounsAny = [
    "achiever",
    "actor",
    "animal ",
    "answer",
    "ant",
    "apparatus",
    "apple",
    "argument",
    "arm",
    "army",
    "attack",
    "attempt",
    "attention",
    "attraction",
    "aunt",
    "authority",
    "baby ",
    "badge",
    "bag",
    "bait",
    "ball",
    "balloon",
    "banana",
    "band",
    "base",
    "bat",
    "beam",
    "bean",
    "bear",
    "beast",
    "bed",
    "bee",
    "beef",
    "beetle",
    "beggar",
    "beginner",
    "belief",
    "bell",
    "berry",
    "bike",
    "bird",
    "birthday",
    "bit",
    "blade",
    "blood",
    "blow",
    "boat",
    "body",
    "bomb",
    "bone",
    "book",
    "boot",
    "bottle",
    "box",
    "boy",
    "brain",
    "brick",
    "brother",
    "bubble",
    "bucket",
    "building",
    "bun",
    "burn",
    "business",
    "cabbage",
    "cactus",
    "cake",
    "calculator",
    "cannon",
    "cap",
    "card",
    "carpenter",
    "cat",
    "cause",
    "cemetery",
    "chain",
    "chance",
    "change",
    "cheese",
    "cherry",
    "chicken ",
    "children",
    "chin",
    "circle",
    "clock",
    "cloud",
    "clover",
    "club",
    "coach",
    "coast",
    "coil",
    "color",
    "committee",
    "company",
    "competition",
    "condition",
    "connection",
    "control",
    "cook",
    "copy",
    "country",
    "cow",
    "cracker",
    "creator",
    "creature",
    "crook",
    "crow",
    "crowd",
    "crown",
    "crush",
    "cry",
    "cub",
    "current",
    "dad",
    "daughter",
    "death",
    "deer",
    "desire",
    "destruction",
    "detail",
    "development",
    "dinosaurs ",
    "direction",
    "dirt",
    "discovery",
    "discussion",
    "disease",
    "dock",
    "doctor",
    "dog",
    "doll",
    "donkey",
    "door",
    "dress",
    "drink",
    "drug",
    "duck ",
    "ear",
    "edge",
    "effect",
    "egg",
    "elbow",
    "end",
    "engine",
    "error",
    "event",
    "example",
    "experience",
    "expert",
    "eye",
    "face",
    "fact",
    "family",
    "fan",
    "farmer ",
    "father",
    "fear",
    "feast",
    "feather",
    "feeling",
    "fiction",
    "fight",
    "finger",
    "fire ",
    "fireman",
    "fish",
    "flag",
    "flame",
    "flower",
    "food",
    "foot",
    "force",
    "friend",
    "frog",
    "fruit",
    "fuel",
    "game",
    "gardener",
    "gate",
    "ghost",
    "giant",
    "giraffe",
    "girl",
    "goat",
    "goldfish",
    "goose",
    "government",
    "governor",
    "grandfather",
    "grandmother",
    "guide",
    "guitar",
    "gun",
    "hair",
    "haircut",
    "hammer",
    "hand",
    "hate",
    "head",
    "health",
    "heart",
    "heat",
    "help",
    "hen",
    "hole",
    "hope",
    "horse",
    "house",
    "ice",
    "icicle",
    "idea",
    "impulse",
    "insect",
    "interest",
    "invention",
    "jellyfish",
    "jewel",
    "joke",
    "journey",
    "judge",
    "key",
    "kiss",
    "kite",
    "kitten",
    "kitty ",
    "knee",
    "knife",
    "knowledge",
    "laborer",
    "ladybug",
    "lamp",
    "laugh",
    "lawyer",
    "lead",
    "leaf",
    "leg ",
    "letter",
    "lettuce",
    "light",
    "limit",
    "lizard ",
    "lock",
    "locket",
    "love",
    "machine",
    "magic",
    "maid",
    "man",
    "manager",
    "map",
    "mask",
    "match",
    "memory",
    "mind",
    "minister",
    "mom",
    "monkey",
    "moon",
    "mother",
    "mouth",
    "muscle",
    "music",
    "name",
    "nation",
    "need",
    "night",
    "noise",
    "nose",
    "note",
    "number",
    "nut",
    "observation",
    "ocean",
    "offer",
    "officer",
    "opinion",
    "order",
    "organization",
    "owl",
    "owner",
    "page",
    "pain",
    "parent",
    "partner",
    "party",
    "passenger",
    "peace",
    "person",
    "pest",
    "pet",
    "picture",
    "pie",
    "pig",
    "place",
    "plant",
    "pleasure",
    "plot",
    "point",
    "poison",
    "police",
    "prince",
    "prisoner",
    "protester",
    "punishment",
    "purpose",
    "queen",
    "question",
    "quill",
    "rabbit ",
    "rain",
    "rainstorm",
    "rat",
    "reason",
    "regret",
    "religion",
    "representative",
    "reward",
    "riddle",
    "river",
    "rock",
    "root",
    "rose",
    "scarecrow",
    "scientist",
    "sea",
    "secretary",
    "self",
    "sense",
    "servant",
    "shade",
    "sheep",
    "ship",
    "sister",
    "slave",
    "smell",
    "smile",
    "snail",
    "snake",
    "son",
    "song",
    "sound",
    "space",
    "spider",
    "spy",
    "square",
    "squirrel",
    "star",
    "statement",
    "stomach",
    "stone",
    "story",
    "stranger",
    "suggestion",
    "suit",
    "supporter",
    "surprise",
    "tank",
    "taste",
    "teacher",
    "theory",
    "thing",
    "thought",
    "thrill",
    "thunder",
    "tiger",
    "time",
    "toad",
    "toy ",
    "tree",
    "trouble",
    "uncle",
    "value",
    "vegetable",
    "visitor",
    "voice",
    "voyage",
    "war",
    "wave",
    "wheel",
    "whip",
    "wind ",
    "window ",
    "winter",
    "wish",
    "woman",
    "word",
    "work",
    "worm",
    "wound",
    "writer"
];

jsrpg.random._arrayNounsPeople = [
    "achiever",
    "actor",
    "animal ",
    "aunt",
    "baby ",
    "beast",
    "beggar",
    "beginner",
    "brain",
    "brother",
    "calculator",
    "carpenter",
    "children",
    "coach",
    "cook",
    "copy",
    "cracker",
    "creator",
    "creature",
    "crook",
    "cub",
    "dad",
    "daughter",
    "doctor",
    "dog",
    "donkey",
    "expert",
    "farmer ",
    "father",
    "fireman",
    "friend",
    "gardener",
    "ghost",
    "giant",
    "girl",
    "goldfish",
    "governor",
    "grandfather",
    "grandmother",
    "guide",
    "inventor",
    "judge",
    "laborer",
    "lawyer",
    "leader",
    "wizard ",
    "maid",
    "man",
    "manager",
    "minister",
    "mom",
    "monkey",
    "mother",
    "muscle",
    "officer",
    "owner",
    "page",
    "parent",
    "partner",
    "passenger",
    "person",
    "pet",
    "pig",
    "police",
    "prince",
    "prisoner",
    "protester",
    "punisher",
    "queen",
    "rat",
    "representative",
    "scarecrow",
    "scientist",
    "secretary",
    "servant",
    "sister",
    "slave",
    "snake",
    "son",
    "spider",
    "spy",
    "squirrel",
    "stranger",
    "supporter",
    "teacher",
    "theorist",
    "thing",
    "tiger",
    "toad",
    "uncle",
    "visitor",
    "warrior",
    "woman",
    "worker",
    "worm",
    "writer"
];

jsrpg.random._arrayNounsColors = [
    "Mahogany",
    "Fuzzy Wuzzy Brown",
    "Chestnut",
    "Red Orange",
    "Sunset Orange",
    "Bittersweet",
    "Melon",
    "Outrageous Orange",
    "Vivid Tangerine",
    "Burnt Sienna",
    "Brown",
    "Sepia",
    "Orange",
    "Burnt Orange",
    "Copper",
    "Mango Tango",
    "Atomic Tangerine",
    "Beaver",
    "Antique Brass",
    "Desert Sand",
    "Raw Sienna",
    "Tumbleweed",
    "Tan",
    "Peach",
    "Macaroni and Cheese",
    "Apricot",
    "Neon Carrot",
    "Almond",
    "Yellow Orange",
    "Gold",
    "Shadow",
    "Banana Mania",
    "Sunglow",
    "Goldenrod",
    "Dandelion",
    "Yellow",
    "Green Yellow",
    "Spring Green",
    "Olive Green",
    "Laser Lemon",
    "Unmellow Yellow",
    "Canary",
    "Yellow Green",
    "Inch Worm",
    "Asparagus",
    "Granny Smith Apple",
    "Electric Lime",
    "Screamin Green",
    "Fern",
    "Forest Green",
    "Sea Green",
    "Green",
    "Mountain Meadow",
    "Shamrock",
    "Jungle Green",
    "Caribbean Green",
    "Tropical Rain Forest",
    "Pine Green",
    "Robin Egg Blue",
    "Aquamarine",
    "Turquoise Blue",
    "Sky Blue",
    "Outer Space",
    "Blue Green",
    "Pacific Blue",
    "Cerulean",
    "Cornflower",
    "Midnight Blue",
    "Navy Blue",
    "Denim",
    "Blue",
    "Periwinkle",
    "Cadet Blue",
    "Indigo",
    "Wild Blue Yonder",
    "Manatee",
    "Blue Bell",
    "Blue Violet",
    "Purple Heart",
    "Royal Purple",
    "Purple Mountains’ Majesty",
    "Purple",
    "Wisteria",
    "Vivid Violet",
    "Fuchsia",
    "Shocking Pink",
    "Pink Flamingo",
    "Plum",
    "Hot Magenta",
    "Purple Pizzazz",
    "Razzle Dazzle Rose",
    "Orchid",
    "Red Violet",
    "Eggplant",
    "Cerise",
    "Wild Strawberry",
    "Magenta",
    "Lavender",
    "Cotton Candy",
    "Violet Red",
    "Carnation Pink",
    "Razzmatazz",
    "Piggy Pink",
    "Jazzberry Jam",
    "Blush",
    "Tickle Me Pink",
    "Pink Sherbet",
    "Maroon",
    "Red",
    "Radical Red",
    "Mauvelous",
    "Wild Watermelon",
    "Scarlet",
    "Salmon",
    "Brick Red",
    "White",
    "Timberwolf",
    "Silver",
    "Gray",
    "Black"
];

jsrpg.random.nounAny = function() {
    return jsrpg.random.randomArray(jsrpg.random._arrayNounsAny);
};

jsrpg.random.nounPersonal = function() {
    return jsrpg.random.randomArray(jsrpg.random._arrayNounsPeople);
};

jsrpg.random.nounColor = function() {
    return jsrpg.random.randomArray(jsrpg.random._arrayNounsColors);
};
