/* @namespace Namespace para API JSRPG */
var jsrpg = jsrpg || {};

/**
 * Dado de número de caras indicado
 * @param caras
 * @returns {number} Entre 1 y caras
 */
jsrpg.d = function(caras) {
    return Math.floor(Math.random() * caras) + 1;
};

/**
 * Devuelve una cadena con el modificador y el signo +/-
 * @param modificador
 * @returns {string}
 */
jsrpg.modBonito = function(modificador) {
    if (modificador < 0) {
        return String(modificador);
    } else {
        return "+" + String(modificador);
    }
};

/**
 *
 * @param {number} rango Número de caras del dado que se usa para consultar la tabla
 * @param {{v:number,e:*}[]} valores
 * @constructor
 */
jsrpg.Tabla = function(rango, valores) {
    this.rango = rango;

    this.valores = valores;
};

jsrpg.Tabla.REROLL = "REROLL";

jsrpg.Tabla.prototype = {
    constructor : jsrpg.Tabla,

    /**
     *
     * @returns {*}
     */
    tira : function() {
        var tirada = jsrpg.d(this.rango);
        var valor;

        for (var i = 0; i < this.valores.length; i++) {
            if (this.valores[i].v >= tirada) {
                valor = this.valores[i].e;
                break;
            }
        }

        return valor;
    }
};

jsrpg.locale = {};

jsrpg.locale.idiomas = {};
jsrpg.locale.idiomas.eng = "eng";
jsrpg.locale.idiomas.spa = "spa";

jsrpg.locale.idioma_ui = jsrpg.locale.idiomas.eng;

jsrpg.locale.diccionario = {};

/**
 *
 * @param {string} id
 * @param {string} eng
 * @param {string} spa
 * @returns {string}
 * @public
 */
jsrpg.locale.d = function(id, eng, spa) {
    jsrpg.locale.diccionario[id] = {
        eng: eng,
        spa: spa
    };
    return id;
};

/**
 *
 * @param {string} id
 * @returns {string}
 * @public
 */
jsrpg.locale.l = function(id) {
    if (jsrpg.locale.diccionario[id])
        return jsrpg.locale.diccionario[id][jsrpg.locale.idioma_ui];
    else
        return id;
};

/**
 * Ofrece una selección al usuario en una ventana emergente
 * @param {{opciones:{texto:string,valor:string}[],callback:Function}} parametros
 */
jsrpg.userChoice = function(parametros) {
    var ventana = $("<div></div>");

    var botones = [];

    var opciones = parametros.opciones;

    var elecciones = parametros.elecciones;
    var numElecciones = 0;

    var generaBotonSencillo = function(texto, valor, callback) {
        return {
            text: texto,
            click: function() {
                $(ventana).dialog("close");
                callback.call(document,valor);
            }
        };
    };

    var generaBotonMultiple = function(texto, valor, tipo) {
        var boton = $("<button></button>").append(texto);

        boton.addClass("jsrpg-button");
        boton.attr("valor",valor);

        if (tipo) {
            boton.attr("tipo",tipo);
        }

        boton.on("click", function() {
                if ($(this).hasClass("jsrpg-option-selected")) {
                    if (numElecciones > 0) {
                        $(this).removeClass("jsrpg-option-selected");
                        numElecciones--;
                    }
                } else {
                    if (numElecciones < elecciones) {
                        $(this).addClass("jsrpg-option-selected");
                        numElecciones++;
                    }
                }
            }
        );
        return boton;
    };

    if (parametros.multiple) {
        if (parametros.opcionesAgrupadas) {
            botones.push(generaBotonSencillo("OK","",function() {
                if (numElecciones == elecciones) {
                    var opcionesElegidas = [];

                    $(ventana).find(".jsrpg-button.jsrpg-option-selected").each(function(index, element) {
                        opcionesElegidas.push({valor:$(element).attr("valor"),tipo:$(element).attr("tipo")});
                    });
                    $(ventana).dialog("close");
                    $(ventana).empty();
                    parametros.callback(opcionesElegidas);
                }
            }));
            for (i = 0; i < opciones.length; i++) {
                $(ventana).append($("<h3></h3>").append(jsrpg.locale.l(opciones[i].tipo)));
                for (var j = 0; j < opciones[i].opciones.length; j++) {
                    $(ventana).append(generaBotonMultiple(opciones[i].opciones[j].texto,opciones[i].opciones[j].valor,opciones[i].tipo));
                }
            }
        } else {
            botones.push(generaBotonSencillo("OK","",function() {
                if (numElecciones == elecciones) {
                    var opcionesElegidas = [];

                    $(ventana).find(".jsrpg-button.jsrpg-option-selected").each(function(index, element) {
                        opcionesElegidas.push($(element).attr("valor"));

                    });
                    $(ventana).dialog("close");
                    $(ventana).empty();
                    parametros.callback(opcionesElegidas);
                }
            }));
            for (i = 0; i < opciones.length; i++) {
                $(ventana).append(generaBotonMultiple(opciones[i].texto,opciones[i].valor));
            }
        }
    } else {
        for (var i = 0; i < opciones.length; i++) {
            botones.push(generaBotonSencillo(opciones[i].texto,opciones[i].valor,opciones[i].callback || parametros.callback ));
        }
    }

    ventana.dialog({
        title:parametros.titulo,
        autoOpen:true,
        buttons: botones,
        width: 800
    });
};

/**
 *
 * @type {number}
 */
jsrpg.idElecciones = 10;

/**
 *
 * @param {*} modelo
 * @param {Function} aplicar Función para aplicar al modelo la elección hecha
 * @param {Function} cambiar Función para rehacer la elección. Recibe un parametro callback al que debe llamar al terminar.
 * @param {Function} eliminar Función para deshacer la elección hecha sobre el modelo
 * @param {string} descripcion Descripción de la elección
 * @param {{}} opciones
 * @constructor
 */
jsrpg.Eleccion = function(modelo, aplicar, cambiar, eliminar, descripcion, opciones) {

    /**
     *
     * @type {number}
     */
    this.id = jsrpg.idElecciones++;

    /**
     *
     * @type {*}
     */
    this.modelo = modelo;

    /**
     *
     * @type {Function}
     */
    this.aplicar = aplicar;

    /**
     *
     * @type {Function}
     */
    this.cambiar = cambiar;

    /**
     *
     * @type {Function}
     */
    this.eliminar = eliminar;

    /**
     *
     * @type {string}
     */
    this.descripcion = descripcion;

    /**
     *
     * @type {{}}
     */
    this.opciones = opciones;
};

jsrpg.Eleccion.prototype = {
    constructor : jsrpg.Eleccion,

    activar : function() {
        this.aplicar.call(this.model);
    },

    desactivar : function() {
        this.eliminar.call(this.model);
    },

    actualizar : function(callback) {
        this.cambiar.call(this, callback);
    },

    isEliminable : function() {
        return this.opciones.eliminable;
    },

    isCambiable : function() {
        return this.opciones.cambiable;
    }

};

/**
 *
 * @type {jsrpg.Eleccion[]}
 */
jsrpg.elecciones = [];

/**
 *
 * @param {*} modelo
 * @param {Function} aplicar
 * @param {Function} cambiar
 * @param {Function} eliminar
 * @param {string} descripcion
 * @param {{}} opciones
 * @returns {number} El ID de control.
 */
jsrpg.addEleccion = function(modelo, aplicar, cambiar, eliminar, descripcion, opciones) {
    var eleccion = new jsrpg.Eleccion(modelo, aplicar, cambiar, eliminar, descripcion, opciones);
    eleccion.activar();
    jsrpg.elecciones.push(eleccion);
    return eleccion.id;
};

/**
 *
 * @param {number} id
 */
jsrpg.removeEleccion = function(id) {
    var i;
    var eleccion;

    var indiceEliminado = -1;

    for (i = 0; i < jsrpg.elecciones.length; i++) {
        if (jsrpg.elecciones[i].id == id) {
            indiceEliminado = i;
            break;
        }
    }

    if (indiceEliminado != -1) {
        for (i = jsrpg.elecciones.length-1; i >= indiceEliminado; i--) {
            eleccion = jsrpg.elecciones[i];
            eleccion.desactivar();
        }


        if (!eleccion.opciones['EliminarAislado']) {
            jsrpg.elecciones.splice(indiceEliminado,1);
            for (i = indiceEliminado; i < jsrpg.elecciones.length; i++) {
                eleccion = jsrpg.elecciones[i];

                eleccion.activar();
            }
        } else {
            if (indiceEliminado == 0) {
                jsrpg.elecciones = [];
            } else {
                jsrpg.elecciones = jsrpg.elecciones.slice(0,indiceEliminado-1);
            }
        }
    }
};

/**
 *
 * @param {number} id
 */
jsrpg.updateEleccion = function(id) {
    var i;
    var eleccion;

    var indiceCambiado = -1;

    for (i = 0; i < jsrpg.elecciones.length; i++) {
        if (jsrpg.elecciones[i].id == id) {
            indiceCambiado = i;
            break;
        }
    }

    if (indiceCambiado != -1) {
        for (i = jsrpg.elecciones.length-1; i >= indiceCambiado; i--) {
            eleccion = jsrpg.elecciones[i];
            eleccion.desactivar();
        }
        eleccion = jsrpg.elecciones[indiceCambiado];

        eleccion.actualizar(
            function(eleccion,indiceCambiado){
                return function() {
                    if (!eleccion.opciones['CambiarAislado']) {
                        for (i = indiceCambiado; i < jsrpg.elecciones.length; i++) {
                            eleccion = jsrpg.elecciones[i];

                            eleccion.activar();
                        }
                    } else {
                        jsrpg.elecciones = jsrpg.elecciones.slice(0,indiceCambiado);
                    }
                }
            }(eleccion,indiceCambiado)
        );
    }
};


jsrpg.listaElecciones = function() {
    var listado = [];

    for (var i = 0; i < jsrpg.elecciones.length;i++) {
        listado.push(jsrpg.elecciones[i].descripcion);
    }

    return listado;
};

jsrpg.random = {};

//region words lists
jsrpg.random._arrayAdjectives = [
    "aback",
    "abaft",
    "abandoned",
    "abashed",
    "aberrant",
    "abhorrent",
    "abiding",
    "abject",
    "ablaze",
    "able",
    "abnormal",
    "aboard",
    "aboriginal",
    "abortive",
    "abounding",
    "abrasive",
    "abrupt",
    "absent",
    "absolute",
    "absorbed",
    "absorbing",
    "abstracted",
    "absurd",
    "abundant",
    "abusive",
    "academic",
    "acceptable",
    "accessible",
    "accidental",
    "acclaimed",
    "accomplished",
    "accurate",
    "aching",
    "acid",
    "acidic",
    "acoustic",
    "acrid",
    "acrobatic",
    "active",
    "actual",
    "actually",
    "ad hoc",
    "adamant",
    "adaptable",
    "addicted",
    "adept",
    "adhesive",
    "adjoining",
    "admirable",
    "admired",
    "adolescent",
    "adorable",
    "adored",
    "advanced",
    "adventurous",
    "affectionate",
    "afraid",
    "aged",
    "aggravating",
    "aggressive",
    "agile",
    "agitated",
    "agonizing",
    "agreeable",
    "ahead",
    "ajar",
    "alarmed",
    "alarming",
    "alcoholic",
    "alert",
    "alienated",
    "alike",
    "alive",
    "all",
    "alleged",
    "alluring",
    "aloof",
    "altruistic",
    "amazing",
    "ambiguous",
    "ambitious",
    "ample",
    "amuck",
    "amused",
    "amusing",
    "anchored",
    "ancient",
    "angelic",
    "angry",
    "anguished",
    "animated",
    "annoyed",
    "annoying",
    "annual",
    "another",
    "antique",
    "anxious",
    "any",
    "apathetic",
    "apprehensive",
    "appropriate",
    "apt",
    "aquatic",
    "arctic",
    "arid",
    "aromatic",
    "arrogant",
    "artistic",
    "ashamed",
    "aspiring",
    "assorted",
    "assured",
    "astonishing",
    "athletic",
    "attached",
    "attentive",
    "attractive",
    "auspicious",
    "austere",
    "authentic",
    "authorized",
    "automatic",
    "available",
    "avaricious",
    "average",
    "awake",
    "aware",
    "awesome",
    "awful",
    "awkward",
    "axiomatic",
    "babyish",
    "back",
    "bad",
    "baggy",
    "barbarous",
    "bare",
    "barren",
    "bashful",
    "basic",
    "bawdy",
    "beautiful",
    "befitting",
    "belated",
    "belligerent",
    "beloved",
    "beneficial",
    "bent",
    "berserk",
    "best",
    "better",
    "bewildered",
    "bewitched",
    "big",
    "big-hearted",
    "billowy",
    "biodegradable",
    "bite-sized",
    "bitter",
    "bizarre",
    "black",
    "black-and-white",
    "bland",
    "blank",
    "blaring",
    "bleak",
    "blind",
    "blissful",
    "blond",
    "bloody",
    "blue",
    "blue-eyed",
    "blushing",
    "bogus",
    "boiling",
    "bold",
    "bony",
    "boorish",
    "bored",
    "boring",
    "bossy",
    "both",
    "bouncy",
    "boundless",
    "bountiful",
    "bowed",
    "brainy",
    "brash",
    "brave",
    "brawny",
    "breakable",
    "breezy",
    "brief",
    "bright",
    "brilliant",
    "brisk",
    "broad",
    "broken",
    "bronze",
    "brown",
    "bruised",
    "bubbly",
    "bulky",
    "bumpy",
    "buoyant",
    "burdensome",
    "burly",
    "bustling",
    "busy",
    "buttery",
    "buzzing",
    "cagey",
    "calculating",
    "callous",
    "calm",
    "candid",
    "canine",
    "capable",
    "capital",
    "capricious",
    "carefree",
    "careful",
    "careless",
    "caring",
    "cautious",
    "cavernous",
    "ceaseless",
    "celebrated",
    "certain",
    "changeable",
    "charming",
    "cheap",
    "cheerful",
    "cheery",
    "chemical",
    "chief",
    "childlike",
    "chilly",
    "chivalrous",
    "chubby",
    "chunky",
    "circular",
    "clammy",
    "classic",
    "classy",
    "clean",
    "clear",
    "clear-cut",
    "clever",
    "cloistered",
    "close",
    "closed",
    "cloudy",
    "clueless",
    "clumsy",
    "cluttered",
    "coarse",
    "coherent",
    "cold",
    "colorful",
    "colorless",
    "colossal",
    "combative",
    "comfortable",
    "common",
    "compassionate",
    "competent",
    "complete",
    "complex",
    "complicated",
    "composed",
    "concerned",
    "concrete",
    "condemned",
    "confused",
    "conscious",
    "considerate",
    "constant",
    "content",
    "conventional",
    "cooing",
    "cooked",
    "cool",
    "cooperative",
    "coordinated",
    "corny",
    "corrupt",
    "costly",
    "courageous",
    "courteous",
    "cowardly",
    "crabby",
    "crafty",
    "craven",
    "crazy",
    "creamy",
    "creative",
    "creepy",
    "criminal",
    "crisp",
    "critical",
    "crooked",
    "crowded",
    "cruel",
    "crushing",
    "cuddly",
    "cultivated",
    "cultured",
    "cumbersome",
    "curious",
    "curly",
    "curved",
    "curvy",
    "cut",
    "cute",
    "cylindrical",
    "cynical",
    "daffy",
    "daily",
    "damaged",
    "damaging",
    "damp",
    "dangerous",
    "dapper",
    "daring",
    "dark",
    "darling",
    "dashing",
    "dazzling",
    "dead",
    "deadly",
    "deadpan",
    "deafening",
    "dear",
    "dearest",
    "debonair",
    "decent",
    "decimal",
    "decisive",
    "decorous",
    "deep",
    "deeply",
    "defeated",
    "defective",
    "defenseless",
    "defensive",
    "defiant",
    "deficient",
    "definite",
    "definitive",
    "delayed",
    "delectable",
    "delicate",
    "delicious",
    "delightful",
    "delirious",
    "demanding",
    "demonic",
    "dense",
    "dental",
    "dependable",
    "dependent",
    "depressed",
    "deranged",
    "descriptive",
    "deserted",
    "detailed",
    "determined",
    "devilish",
    "devoted",
    "didactic",
    "different",
    "difficult",
    "digital",
    "diligent",
    "dim",
    "dimpled",
    "dimwitted",
    "direct",
    "direful",
    "dirty",
    "disagreeable",
    "disastrous",
    "discreet",
    "discrete",
    "disfigured",
    "disguised",
    "disgusted",
    "disgusting",
    "dishonest",
    "disillusioned",
    "disloyal",
    "dismal",
    "dispensable",
    "distant",
    "distinct",
    "distorted",
    "disturbed",
    "divergent",
    "dizzy",
    "domineering",
    "dopey",
    "doting",
    "double",
    "doubtful",
    "downright",
    "drab",
    "draconian",
    "drafty",
    "dramatic",
    "dreary",
    "droopy",
    "drunk",
    "dry",
    "dual",
    "dull",
    "dusty",
    "dutiful",
    "dynamic",
    "dysfunctional",
    "each",
    "eager",
    "early",
    "earnest",
    "earsplitting",
    "earthy",
    "easy",
    "easy-going",
    "eatable",
    "economic",
    "ecstatic",
    "edible",
    "educated",
    "efficacious",
    "efficient",
    "eight",
    "elaborate",
    "elastic",
    "elated",
    "elderly",
    "electric",
    "elegant",
    "elementary",
    "elfin",
    "elite",
    "elliptical",
    "embarrassed",
    "embellished",
    "eminent",
    "emotional",
    "empty",
    "enchanted",
    "enchanting",
    "encouraging",
    "endurable",
    "energetic",
    "enlightened",
    "enormous",
    "enraged",
    "entertaining",
    "enthusiastic",
    "entire",
    "envious",
    "equable",
    "equal",
    "equatorial",
    "erect",
    "erratic",
    "essential",
    "esteemed",
    "ethereal",
    "ethical",
    "euphoric",
    "evanescent",
    "evasive",
    "even",
    "evergreen",
    "everlasting",
    "every",
    "evil",
    "exalted",
    "excellent",
    "excitable",
    "excited",
    "exciting",
    "exclusive",
    "exemplary",
    "exhausted",
    "exotic",
    "expensive",
    "experienced",
    "expert",
    "extra-large",
    "extra-small",
    "extraneous",
    "extroverted",
    "exuberant",
    "exultant",
    "fabulous",
    "faded",
    "failing",
    "faint",
    "fair",
    "faithful",
    "fake",
    "fallacious",
    "false",
    "familiar",
    "famous",
    "fanatical",
    "fancy",
    "fantastic",
    "far",
    "far-flung",
    "far-off",
    "faraway",
    "fascinated",
    "fast",
    "fat",
    "fatal",
    "fatherly",
    "faulty",
    "favorable",
    "favorite",
    "fearful",
    "fearless",
    "feeble",
    "feigned",
    "feisty",
    "feline",
    "female",
    "feminine",
    "fertile",
    "festive",
    "few",
    "fickle",
    "fierce",
    "filthy",
    "fine",
    "finicky",
    "finished",
    "firm",
    "first",
    "firsthand",
    "fitting",
    "five",
    "fixed",
    "flagrant",
    "flaky",
    "flamboyant",
    "flashy",
    "flat",
    "flawed",
    "flawless",
    "flickering",
    "flimsy",
    "flippant",
    "flowery",
    "fluffy",
    "fluid",
    "flustered",
    "fluttering",
    "foamy",
    "focused",
    "fond",
    "foolhardy",
    "foolish",
    "forceful",
    "foregoing",
    "forgetful",
    "forked",
    "formal",
    "forsaken",
    "forthright",
    "fortunate",
    "four",
    "fragile",
    "fragrant",
    "frail",
    "frank",
    "frantic",
    "frayed",
    "free",
    "freezing",
    "frequent",
    "fresh",
    "fretful",
    "friendly",
    "frightened",
    "frightening",
    "frigid",
    "frilly",
    "frivolous",
    "frizzy",
    "front",
    "frosty",
    "frozen",
    "frugal",
    "fruitful",
    "full",
    "fumbling",
    "functional",
    "funny",
    "furry",
    "furtive",
    "fussy",
    "future",
    "futuristic",
    "fuzzy",
    "gabby",
    "gainful",
    "gamy",
    "gaping",
    "gargantuan",
    "garrulous",
    "gaseous",
    "gaudy",
    "general",
    "generous",
    "gentle",
    "genuine",
    "giant",
    "giddy",
    "gifted",
    "gigantic",
    "giving",
    "glamorous",
    "glaring",
    "glass",
    "gleaming",
    "gleeful",
    "glib",
    "glistening",
    "glittering",
    "gloomy",
    "glorious",
    "glossy",
    "glum",
    "godly",
    "golden",
    "good",
    "good-natured",
    "goofy",
    "gorgeous",
    "graceful",
    "gracious",
    "grand",
    "grandiose",
    "granular",
    "grateful",
    "gratis",
    "grave",
    "gray",
    "greasy",
    "great",
    "greedy",
    "green",
    "gregarious",
    "grey",
    "grieving",
    "grim",
    "grimy",
    "gripping",
    "grizzled",
    "groovy",
    "gross",
    "grotesque",
    "grouchy",
    "grounded",
    "growing",
    "growling",
    "grown",
    "grubby",
    "gruesome",
    "grumpy",
    "guarded",
    "guiltless",
    "guilty",
    "gullible",
    "gummy",
    "gusty",
    "guttural",
    "habitual",
    "hairy",
    "half",
    "hallowed",
    "halting",
    "handmade",
    "handsome",
    "handsomely",
    "handy",
    "hanging",
    "hapless",
    "happy",
    "happy-go-lucky",
    "hard",
    "hard-to-find",
    "harmful",
    "harmless",
    "harmonious",
    "harsh",
    "hasty",
    "hateful",
    "haunting",
    "heady",
    "healthy",
    "heartbreaking",
    "heartfelt",
    "hearty",
    "heavenly",
    "heavy",
    "hefty",
    "hellish",
    "helpful",
    "helpless",
    "hesitant",
    "hidden",
    "hideous",
    "high",
    "high-level",
    "high-pitched",
    "highfalutin",
    "hilarious",
    "hissing",
    "historical",
    "hoarse",
    "holistic",
    "hollow",
    "homeless",
    "homely",
    "honest",
    "honorable",
    "honored",
    "hopeful",
    "horrible",
    "hospitable",
    "hot",
    "huge",
    "hulking",
    "humble",
    "humdrum",
    "humiliating",
    "humming",
    "humongous",
    "humorous",
    "hungry",
    "hurried",
    "hurt",
    "hurtful",
    "hushed",
    "husky",
    "hypnotic",
    "hysterical",
    "icky",
    "icy",
    "ideal",
    "idealistic",
    "identical",
    "idiotic",
    "idle",
    "idolized",
    "ignorant",
    "ill",
    "ill-fated",
    "ill-informed",
    "illegal",
    "illiterate",
    "illustrious",
    "imaginary",
    "imaginative",
    "immaculate",
    "immaterial",
    "immediate",
    "immense",
    "imminent",
    "impartial",
    "impassioned",
    "impeccable",
    "imperfect",
    "imperturbable",
    "impish",
    "impolite",
    "important",
    "imported",
    "impossible",
    "impractical",
    "impressionable",
    "impressive",
    "improbable",
    "impure",
    "inborn",
    "incandescent",
    "incomparable",
    "incompatible",
    "incompetent",
    "incomplete",
    "inconclusive",
    "inconsequential",
    "incredible",
    "indelible",
    "indolent",
    "industrious",
    "inexpensive",
    "inexperienced",
    "infamous",
    "infantile",
    "infatuated",
    "inferior",
    "infinite",
    "informal",
    "innate",
    "innocent",
    "inquisitive",
    "insecure",
    "insidious",
    "insignificant",
    "insistent",
    "instinctive",
    "instructive",
    "insubstantial",
    "intelligent",
    "intent",
    "intentional",
    "interesting",
    "internal",
    "international",
    "intrepid",
    "invincible",
    "irate",
    "ironclad",
    "irresponsible",
    "irritating",
    "itchy",
    "jaded",
    "jagged",
    "jam-packed",
    "jaunty",
    "jazzy",
    "jealous",
    "jittery",
    "jobless",
    "joint",
    "jolly",
    "jovial",
    "joyful",
    "joyous",
    "jubilant",
    "judicious",
    "juicy",
    "jumbled",
    "jumbo",
    "jumpy",
    "junior",
    "juvenile",
    "kaleidoscopic",
    "kaput",
    "keen",
    "key",
    "kind",
    "kindhearted",
    "kindly",
    "klutzy",
    "knobby",
    "knotty",
    "knowing",
    "knowledgeable",
    "known",
    "kooky",
    "kosher",
    "labored",
    "lackadaisical",
    "lacking",
    "lame",
    "lamentable",
    "languid",
    "lanky",
    "large",
    "last",
    "lasting",
    "late",
    "laughable",
    "lavish",
    "lawful",
    "lazy",
    "leading",
    "leafy",
    "lean",
    "learned",
    "left",
    "legal",
    "legitimate",
    "lethal",
    "level",
    "lewd",
    "light",
    "lighthearted",
    "likable",
    "like",
    "likeable",
    "likely",
    "limited",
    "limp",
    "limping",
    "linear",
    "lined",
    "liquid",
    "literate",
    "little",
    "live",
    "lively",
    "livid",
    "living",
    "loathsome",
    "lone",
    "lonely",
    "long",
    "long-term",
    "longing",
    "loose",
    "lopsided",
    "lost",
    "loud",
    "loutish",
    "lovable",
    "lovely",
    "loving",
    "low",
    "lowly",
    "loyal",
    "lucky",
    "ludicrous",
    "lumbering",
    "luminous",
    "lumpy",
    "lush",
    "lustrous",
    "luxuriant",
    "luxurious",
    "lying",
    "lyrical",
    "macabre",
    "macho",
    "mad",
    "maddening",
    "made-up",
    "madly",
    "magenta",
    "magical",
    "magnificent",
    "majestic",
    "major",
    "makeshift",
    "male",
    "malicious",
    "mammoth",
    "maniacal",
    "many",
    "marked",
    "married",
    "marvelous",
    "masculine",
    "massive",
    "material",
    "materialistic",
    "mature",
    "meager",
    "mealy",
    "mean",
    "measly",
    "meaty",
    "medical",
    "mediocre",
    "medium",
    "meek",
    "mellow",
    "melodic",
    "melted",
    "memorable",
    "menacing",
    "merciful",
    "mere",
    "merry",
    "messy",
    "metallic",
    "mighty",
    "mild",
    "military",
    "milky",
    "mindless",
    "miniature",
    "minor",
    "minty",
    "miscreant",
    "miserable",
    "miserly",
    "misguided",
    "misty",
    "mixed",
    "moaning",
    "modern",
    "modest",
    "moist",
    "moldy",
    "momentous",
    "monstrous",
    "monthly",
    "monumental",
    "moral",
    "mortified",
    "motherly",
    "motionless",
    "mountainous",
    "muddled",
    "muddy",
    "muffled",
    "multicolored",
    "mundane",
    "murky",
    "mushy",
    "musty",
    "mute",
    "muted",
    "mysterious",
    "naive",
    "nappy",
    "narrow",
    "nasty",
    "natural",
    "naughty",
    "nauseating",
    "nautical",
    "near",
    "neat",
    "nebulous",
    "necessary",
    "needless",
    "needy",
    "negative",
    "neglected",
    "negligible",
    "neighboring",
    "neighborly",
    "nervous",
    "new",
    "next",
    "nice",
    "nifty",
    "nimble",
    "nine",
    "nippy",
    "nocturnal",
    "noiseless",
    "noisy",
    "nonchalant",
    "nondescript",
    "nonstop",
    "normal",
    "nostalgic",
    "nosy",
    "notable",
    "noted",
    "noteworthy",
    "novel",
    "noxious",
    "null",
    "numb",
    "numberless",
    "numerous",
    "nutritious",
    "nutty",
    "oafish",
    "obedient",
    "obeisant",
    "obese",
    "oblong",
    "obnoxious",
    "obscene",
    "obsequious",
    "observant",
    "obsolete",
    "obtainable",
    "obvious",
    "occasional",
    "oceanic",
    "odd",
    "oddball",
    "offbeat",
    "offensive",
    "official",
    "oily",
    "old",
    "old-fashioned",
    "omniscient",
    "one",
    "onerous",
    "only",
    "open",
    "opposite",
    "optimal",
    "optimistic",
    "opulent",
    "orange",
    "orderly",
    "ordinary",
    "organic",
    "original",
    "ornate",
    "ornery",
    "ossified",
    "other",
    "our",
    "outgoing",
    "outlandish",
    "outlying",
    "outrageous",
    "outstanding",
    "oval",
    "overconfident",
    "overcooked",
    "overdue",
    "overjoyed",
    "overlooked",
    "overrated",
    "overt",
    "overwrought",
    "painful",
    "painstaking",
    "palatable",
    "pale",
    "paltry",
    "panicky",
    "panoramic",
    "parallel",
    "parched",
    "parsimonious",
    "partial",
    "passionate",
    "past",
    "pastel",
    "pastoral",
    "pathetic",
    "peaceful",
    "penitent",
    "peppery",
    "perfect",
    "perfumed",
    "periodic",
    "perky",
    "permissible",
    "perpetual",
    "personal",
    "pertinent",
    "pesky",
    "pessimistic",
    "petite",
    "petty",
    "phobic",
    "phony",
    "physical",
    "picayune",
    "piercing",
    "pink",
    "piquant",
    "pitiful",
    "placid",
    "plain",
    "plaintive",
    "plant",
    "plastic",
    "plausible",
    "playful",
    "pleasant",
    "pleased",
    "pleasing",
    "plucky",
    "plump",
    "plush",
    "pointed",
    "pointless",
    "poised",
    "polished",
    "polite",
    "political",
    "poor",
    "popular",
    "portly",
    "posh",
    "positive",
    "possessive",
    "possible",
    "potable",
    "powerful",
    "powerless",
    "practical",
    "precious",
    "premium",
    "present",
    "prestigious",
    "pretty",
    "previous",
    "pricey",
    "prickly",
    "primary",
    "prime",
    "pristine",
    "private",
    "prize",
    "probable",
    "productive",
    "profitable",
    "profuse",
    "proper",
    "protective",
    "proud",
    "prudent",
    "psychedelic",
    "psychotic",
    "public",
    "puffy",
    "pumped",
    "punctual",
    "pungent",
    "puny",
    "pure",
    "purple",
    "purring",
    "pushy",
    "putrid",
    "puzzled",
    "puzzling",
    "quack",
    "quaint",
    "qualified",
    "quarrelsome",
    "quarterly",
    "queasy",
    "querulous",
    "questionable",
    "quick",
    "quick-witted",
    "quickest",
    "quiet",
    "quintessential",
    "quirky",
    "quixotic",
    "quizzical",
    "rabid",
    "racial",
    "radiant",
    "ragged",
    "rainy",
    "rambunctious",
    "rampant",
    "rapid",
    "rare",
    "rash",
    "raspy",
    "ratty",
    "raw",
    "ready",
    "real",
    "realistic",
    "reasonable",
    "rebel",
    "recent",
    "receptive",
    "reckless",
    "recondite",
    "rectangular",
    "red",
    "redundant",
    "reflecting",
    "reflective",
    "regal",
    "regular",
    "reliable",
    "relieved",
    "remarkable",
    "reminiscent",
    "remorseful",
    "remote",
    "repentant",
    "repulsive",
    "required",
    "resolute",
    "resonant",
    "respectful",
    "responsible",
    "revolving",
    "rewarding",
    "rhetorical",
    "rich",
    "right",
    "righteous",
    "rightful",
    "rigid",
    "ringed",
    "ripe",
    "ritzy",
    "roasted",
    "robust",
    "romantic",
    "roomy",
    "rosy",
    "rotating",
    "rotten",
    "rough",
    "round",
    "rowdy",
    "royal",
    "rubbery",
    "ruddy",
    "rude",
    "rundown",
    "runny",
    "rural",
    "rustic",
    "rusty",
    "ruthless",
    "sable",
    "sad",
    "safe",
    "salty",
    "same",
    "sandy",
    "sane",
    "sarcastic",
    "sardonic",
    "sassy",
    "satisfied",
    "satisfying",
    "savory",
    "scaly",
    "scandalous",
    "scarce",
    "scared",
    "scary",
    "scattered",
    "scented",
    "scholarly",
    "scientific",
    "scintillating",
    "scornful",
    "scratchy",
    "scrawny",
    "screeching",
    "second",
    "second-hand",
    "secondary",
    "secret",
    "secretive",
    "sedate",
    "seemly",
    "selective",
    "self-assured",
    "self-reliant",
    "selfish",
    "sentimental",
    "separate",
    "serene",
    "serious",
    "serpentine",
    "several",
    "severe",
    "shabby",
    "shadowy",
    "shady",
    "shaggy",
    "shaky",
    "shallow",
    "shameful",
    "shameless",
    "sharp",
    "shimmering",
    "shiny",
    "shivering",
    "shocked",
    "shocking",
    "shoddy",
    "short",
    "short-term",
    "showy",
    "shrill",
    "shut",
    "shy",
    "sick",
    "silent",
    "silky",
    "silly",
    "silver",
    "similar",
    "simple",
    "simplistic",
    "sincere",
    "sinful",
    "single",
    "six",
    "sizzling",
    "skeletal",
    "skillful",
    "skinny",
    "sleepy",
    "slight",
    "slim",
    "slimy",
    "slippery",
    "sloppy",
    "slow",
    "slushy",
    "small",
    "smart",
    "smelly",
    "smiling",
    "smoggy",
    "smooth",
    "smug",
    "snappy",
    "snarling",
    "sneaky",
    "sniveling",
    "snobbish",
    "snoopy",
    "snotty",
    "sociable",
    "soft",
    "soggy",
    "solid",
    "somber",
    "some",
    "sophisticated",
    "sordid",
    "sore",
    "sorrowful",
    "soulful",
    "soupy",
    "sour",
    "sparkling",
    "sparse",
    "special",
    "specific",
    "spectacular",
    "speedy",
    "spherical",
    "spicy",
    "spiffy",
    "spiky",
    "spirited",
    "spiritual",
    "spiteful",
    "splendid",
    "spooky",
    "spotless",
    "spotted",
    "spotty",
    "spry",
    "spurious",
    "squalid",
    "square",
    "squeaky",
    "squealing",
    "squeamish",
    "squiggly",
    "stable",
    "staid",
    "stained",
    "staking",
    "stale",
    "standard",
    "standing",
    "starchy",
    "stark",
    "starry",
    "statuesque",
    "steadfast",
    "steady",
    "steel",
    "steep",
    "stereotyped",
    "sticky",
    "stiff",
    "stimulating",
    "stingy",
    "stormy",
    "straight",
    "strange",
    "strict",
    "strident",
    "striking",
    "striped",
    "strong",
    "studious",
    "stunning",
    "stupendous",
    "stupid",
    "sturdy",
    "stylish",
    "subdued",
    "submissive",
    "subsequent",
    "substantial",
    "subtle",
    "suburban",
    "successful",
    "succinct",
    "sudden",
    "sugary",
    "sulky",
    "sunny",
    "super",
    "superb",
    "superficial",
    "superior",
    "supportive",
    "supreme",
    "sure-footed",
    "surprised",
    "suspicious",
    "svelte",
    "swanky",
    "sweaty",
    "sweet",
    "sweltering",
    "swift",
    "sympathetic",
    "symptomatic",
    "synonymous",
    "taboo",
    "tacit",
    "tacky",
    "talented",
    "talkative",
    "tall",
    "tame",
    "tan",
    "tangible",
    "tangy",
    "tart",
    "tasteful",
    "tasteless",
    "tasty",
    "tattered",
    "taut",
    "tawdry",
    "tearful",
    "tedious",
    "teeming",
    "teeny",
    "teeny-tiny",
    "telling",
    "temporary",
    "tempting",
    "ten",
    "tender",
    "tense",
    "tenuous",
    "tepid",
    "terrible",
    "terrific",
    "tested",
    "testy",
    "thankful",
    "that",
    "therapeutic",
    "these",
    "thick",
    "thin",
    "thinkable",
    "third",
    "thirsty",
    "this",
    "thorny",
    "thorough",
    "those",
    "thoughtful",
    "thoughtless",
    "threadbare",
    "threatening",
    "three",
    "thrifty",
    "thundering",
    "thunderous",
    "tidy",
    "tight",
    "tightfisted",
    "timely",
    "tinted",
    "tiny",
    "tired",
    "tiresome",
    "toothsome",
    "torn",
    "torpid",
    "total",
    "tough",
    "towering",
    "tragic",
    "trained",
    "tranquil",
    "trashy",
    "traumatic",
    "treasured",
    "tremendous",
    "triangular",
    "tricky",
    "trifling",
    "trim",
    "trite",
    "trivial",
    "troubled",
    "truculent",
    "true",
    "trusting",
    "trustworthy",
    "trusty",
    "truthful",
    "tubby",
    "turbulent",
    "twin",
    "two",
    "typical",
    "ubiquitous",
    "ugliest",
    "ugly",
    "ultimate",
    "ultra",
    "unable",
    "unacceptable",
    "unaccountable",
    "unadvised",
    "unarmed",
    "unaware",
    "unbecoming",
    "unbiased",
    "uncomfortable",
    "uncommon",
    "unconscious",
    "uncovered",
    "understated",
    "understood",
    "undesirable",
    "unequal",
    "unequaled",
    "uneven",
    "unfinished",
    "unfit",
    "unfolded",
    "unfortunate",
    "unhappy",
    "unhealthy",
    "uniform",
    "unimportant",
    "uninterested",
    "unique",
    "united",
    "unkempt",
    "unknown",
    "unlawful",
    "unlined",
    "unlucky",
    "unnatural",
    "unpleasant",
    "unrealistic",
    "unripe",
    "unruly",
    "unselfish",
    "unsightly",
    "unsteady",
    "unsuitable",
    "unsung",
    "untidy",
    "untimely",
    "untried",
    "untrue",
    "unused",
    "unusual",
    "unwelcome",
    "unwieldy",
    "unwilling",
    "unwitting",
    "unwritten",
    "upbeat",
    "uppity",
    "upright",
    "upset",
    "uptight",
    "urban",
    "usable",
    "used",
    "useful",
    "useless",
    "utilized",
    "utopian",
    "utter",
    "uttermost",
    "vacant",
    "vacuous",
    "vagabond",
    "vague",
    "vain",
    "valid",
    "valuable",
    "vapid",
    "variable",
    "various",
    "vast",
    "velvety",
    "venerated",
    "vengeful",
    "venomous",
    "verdant",
    "verifiable",
    "versed",
    "vibrant",
    "vicious",
    "victorious",
    "vigilant",
    "vigorous",
    "villainous",
    "violent",
    "violet",
    "virtual",
    "virtuous",
    "visible",
    "vital",
    "vivacious",
    "vivid",
    "voiceless",
    "volatile",
    "voluminous",
    "voracious",
    "vulgar",
    "wacky",
    "waggish",
    "waiting",
    "wakeful",
    "wan",
    "wandering",
    "wanting",
    "warlike",
    "warm",
    "warmhearted",
    "warped",
    "wary",
    "wasteful",
    "watchful",
    "waterlogged",
    "watery",
    "wavy",
    "weak",
    "wealthy",
    "weary",
    "webbed",
    "wee",
    "weekly",
    "weepy",
    "weighty",
    "weird",
    "welcome",
    "well-documented",
    "well-groomed",
    "well-informed",
    "well-lit",
    "well-made",
    "well-off",
    "well-to-do",
    "well-worn",
    "wet",
    "which",
    "whimsical",
    "whirlwind",
    "whispered",
    "whispering",
    "white",
    "whole",
    "wholesale",
    "whopping",
    "wicked",
    "wide",
    "wide-eyed",
    "wiggly",
    "wild",
    "willing",
    "wilted",
    "winding",
    "windy",
    "winged",
    "wiry",
    "wise",
    "wistful",
    "witty",
    "wobbly",
    "woebegone",
    "woeful",
    "womanly",
    "wonderful",
    "wooden",
    "woozy",
    "wordy",
    "workable",
    "worldly",
    "worn",
    "worried",
    "worrisome",
    "worse",
    "worst",
    "worthless",
    "worthwhile",
    "worthy",
    "wrathful",
    "wretched",
    "writhing",
    "wrong",
    "wry",
    "xenophobic",
    "yawning",
    "yearly",
    "yellow",
    "yellowish",
    "yielding",
    "young",
    "youthful",
    "yummy",
    "zany",
    "zealous",
    "zesty",
    "zigzag",
    "zippy",
    "zonked"
];

jsrpg.random._arrayNouns = [
    "achiever",
    "actor",
    "animal ",
    "answer",
    "ant",
    "apparatus",
    "apple",
    "argument",
    "arm",
    "army",
    "attack",
    "attempt",
    "attention",
    "attraction",
    "aunt",
    "authority",
    "baby ",
    "badge",
    "bag",
    "bait",
    "ball",
    "balloon",
    "banana",
    "band",
    "base",
    "bat",
    "beam",
    "bean",
    "bear",
    "beast",
    "bed",
    "bee",
    "beef",
    "beetle",
    "beggar",
    "beginner",
    "belief",
    "bell",
    "berry",
    "bike",
    "bird",
    "birthday",
    "bit",
    "blade",
    "blood",
    "blow",
    "boat",
    "body",
    "bomb",
    "bone",
    "book",
    "boot",
    "bottle",
    "box",
    "boy",
    "brain",
    "brick",
    "brother",
    "bubble",
    "bucket",
    "building",
    "bun",
    "burn",
    "business",
    "cabbage",
    "cactus",
    "cake",
    "calculator",
    "cannon",
    "cap",
    "card",
    "carpenter",
    "cat",
    "cause",
    "cemetery",
    "chain",
    "chance",
    "change",
    "cheese",
    "cherry",
    "chicken ",
    "children",
    "chin",
    "circle",
    "clock",
    "cloud",
    "clover",
    "club",
    "coach",
    "coast",
    "coil",
    "color",
    "committee",
    "company",
    "competition",
    "condition",
    "connection",
    "control",
    "cook",
    "copy",
    "country",
    "cow",
    "cracker",
    "creator",
    "creature",
    "crook",
    "crow",
    "crowd",
    "crown",
    "crush",
    "cry",
    "cub",
    "current",
    "dad",
    "daughter",
    "death",
    "deer",
    "desire",
    "destruction",
    "detail",
    "development",
    "dinosaurs ",
    "direction",
    "dirt",
    "discovery",
    "discussion",
    "disease",
    "dock",
    "doctor",
    "dog",
    "doll",
    "donkey",
    "door",
    "dress",
    "drink",
    "drug",
    "duck ",
    "ear",
    "edge",
    "effect",
    "egg",
    "elbow",
    "end",
    "engine",
    "error",
    "event",
    "example",
    "experience",
    "expert",
    "eye",
    "face",
    "fact",
    "family",
    "fan",
    "farmer ",
    "father",
    "fear",
    "feast",
    "feather",
    "feeling",
    "fiction",
    "fight",
    "finger",
    "fire ",
    "fireman",
    "fish",
    "flag",
    "flame",
    "flower",
    "food",
    "foot",
    "force",
    "friend",
    "frog",
    "fruit",
    "fuel",
    "game",
    "gardener",
    "gate",
    "ghost",
    "giant",
    "giraffe",
    "girl",
    "goat",
    "goldfish",
    "goose",
    "government",
    "governor",
    "grandfather",
    "grandmother",
    "guide",
    "guitar",
    "gun",
    "hair",
    "haircut",
    "hammer",
    "hand",
    "hate",
    "head",
    "health",
    "heart",
    "heat",
    "help",
    "hen",
    "hole",
    "hope",
    "horse",
    "house",
    "ice",
    "icicle",
    "idea",
    "impulse",
    "insect",
    "interest",
    "invention",
    "jellyfish",
    "jewel",
    "joke",
    "journey",
    "judge",
    "key",
    "kiss",
    "kite",
    "kitten",
    "kitty ",
    "knee",
    "knife",
    "knowledge",
    "laborer",
    "ladybug",
    "lamp",
    "laugh",
    "lawyer",
    "lead",
    "leaf",
    "leg ",
    "letter",
    "lettuce",
    "light",
    "limit",
    "lizard ",
    "lock",
    "locket",
    "love",
    "machine",
    "magic",
    "maid",
    "man",
    "manager",
    "map",
    "mask",
    "match",
    "memory",
    "mind",
    "minister",
    "mom",
    "monkey",
    "moon",
    "mother",
    "mouth",
    "muscle",
    "music",
    "name",
    "nation",
    "need",
    "night",
    "noise",
    "nose",
    "note",
    "number",
    "nut",
    "observation",
    "ocean",
    "offer",
    "officer",
    "opinion",
    "order",
    "organization",
    "owl",
    "owner",
    "page",
    "pain",
    "parent",
    "partner",
    "party",
    "passenger",
    "peace",
    "person",
    "pest",
    "pet",
    "picture",
    "pie",
    "pig",
    "place",
    "plant",
    "pleasure",
    "plot",
    "point",
    "poison",
    "police",
    "prince",
    "prisoner",
    "protester",
    "punishment",
    "purpose",
    "queen",
    "question",
    "quill",
    "rabbit ",
    "rain",
    "rainstorm",
    "rat",
    "reason",
    "regret",
    "religion",
    "representative",
    "reward",
    "riddle",
    "river",
    "rock",
    "root",
    "rose",
    "scarecrow",
    "scientist",
    "sea",
    "secretary",
    "self",
    "sense",
    "servant",
    "shade",
    "sheep",
    "ship",
    "sister",
    "slave",
    "smell",
    "smile",
    "snail",
    "snake",
    "son",
    "song",
    "sound",
    "space",
    "spider",
    "spy",
    "square",
    "squirrel",
    "star",
    "statement",
    "stomach",
    "stone",
    "story",
    "stranger",
    "suggestion",
    "suit",
    "supporter",
    "surprise",
    "tank",
    "taste",
    "teacher",
    "theory",
    "thing",
    "thought",
    "thrill",
    "thunder",
    "tiger",
    "time",
    "toad",
    "toy ",
    "tree",
    "trouble",
    "uncle",
    "value",
    "vegetable",
    "visitor",
    "voice",
    "voyage",
    "war",
    "wave",
    "wheel",
    "whip",
    "wind ",
    "window ",
    "winter",
    "wish",
    "woman",
    "word",
    "work",
    "worm",
    "wound",
    "writer"
];

jsrpg.random._arrayVerbs = [
    "abide",
    "accelerate",
    "accept ",
    "accomplish",
    "achieve",
    "acquire",
    "acted",
    "activate",
    "adapt",
    "add ",
    "address",
    "administer",
    "admire ",
    "admit ",
    "adopt",
    "advise ",
    "afford ",
    "agree ",
    "alert",
    "alight",
    "allow ",
    "altered",
    "amuse ",
    "analyze ",
    "announce ",
    "annoy ",
    "answer ",
    "anticipate",
    "apologize ",
    "appear",
    "applaud ",
    "applied",
    "appoint",
    "appraise",
    "appreciate ",
    "approve ",
    "arbitrate",
    "argue ",
    "arise",
    "arrange ",
    "arrest ",
    "arrive ",
    "ascertain",
    "ask",
    "assemble",
    "assess",
    "assist",
    "assure",
    "attach ",
    "attack ",
    "attain",
    "attempt ",
    "attend ",
    "attract ",
    "audited",
    "avoid",
    "awake",
    "back ",
    "bake ",
    "balance ",
    "ban ",
    "bang ",
    "bare ",
    "bat ",
    "bathe ",
    "battle ",
    "be",
    "beam",
    "bear",
    "beat",
    "become",
    "beg ",
    "begin",
    "behave ",
    "behold",
    "belong ",
    "bend",
    "beset",
    "bet",
    "bid",
    "bind",
    "bite",
    "bleach ",
    "bleed",
    "bless ",
    "blind ",
    "blink ",
    "blot ",
    "blow",
    "blush ",
    "boast",
    "boil ",
    "bolt ",
    "bomb ",
    "book ",
    "bore ",
    "borrow ",
    "bounce ",
    "bow ",
    "box ",
    "brake",
    "branch ",
    "break",
    "breathe ",
    "breed",
    "brief",
    "bring",
    "broadcast",
    "bruise ",
    "brush ",
    "bubble ",
    "budget",
    "build",
    "bump ",
    "burn ",
    "burst",
    "bury ",
    "bust",
    "buy",
    "buzz",
    "calculate ",
    "call ",
    "camp ",
    "care ",
    "carry ",
    "carve ",
    "cast",
    "catalog",
    "catch",
    "cause ",
    "challenge ",
    "change ",
    "charge ",
    "chart",
    "chase ",
    "cheat ",
    "check ",
    "cheer ",
    "chew",
    "choke ",
    "choose",
    "chop ",
    "claim ",
    "clap",
    "clarify",
    "classify",
    "clean ",
    "clear ",
    "cling",
    "clip ",
    "close ",
    "clothe",
    "coach ",
    "coil ",
    "collect ",
    "color ",
    "comb ",
    "come",
    "command ",
    "communicate",
    "compare ",
    "compete ",
    "compile",
    "complain ",
    "complete ",
    "compose",
    "compute",
    "conceive",
    "concentrate ",
    "conceptualize",
    "concern ",
    "conclude",
    "conduct",
    "confess ",
    "confront",
    "confuse ",
    "connect ",
    "conserve",
    "consider ",
    "consist ",
    "consolidate",
    "construct",
    "consult",
    "contain ",
    "continue ",
    "contract",
    "control",
    "convert",
    "coordinate",
    "copy ",
    "correct",
    "correlate",
    "cost",
    "cough ",
    "counsel",
    "count ",
    "cover ",
    "crack ",
    "crash ",
    "crawl ",
    "create",
    "creep",
    "critique",
    "cross ",
    "crush ",
    "cry ",
    "cure ",
    "curl ",
    "curve ",
    "cut",
    "cycle",
    "dam ",
    "damage ",
    "dance ",
    "dare ",
    "deal",
    "decay ",
    "deceive ",
    "decide ",
    "decorate ",
    "define",
    "delay ",
    "delegate",
    "delight",
    "deliver ",
    "demonstrate",
    "depend ",
    "describe ",
    "desert ",
    "deserve ",
    "design",
    "destroy ",
    "detail",
    "detect ",
    "determine",
    "develop ",
    "devise",
    "diagnose",
    "dig",
    "direct",
    "disagree ",
    "disappear",
    "disapprove ",
    "disarm ",
    "discover ",
    "dislike ",
    "dispense",
    "display",
    "disprove",
    "dissect",
    "distribute",
    "dive",
    "divert",
    "divide ",
    "do",
    "double ",
    "doubt ",
    "draft",
    "drag ",
    "drain ",
    "dramatize",
    "draw",
    "dream",
    "dress ",
    "drink",
    "drip ",
    "drive",
    "drop ",
    "drown ",
    "drum ",
    "dry ",
    "dust",
    "dwell",
    "earn ",
    "eat",
    "edited",
    "educate ",
    "eliminate",
    "embarrass ",
    "employ ",
    "empty ",
    "enacted",
    "encourage",
    "end ",
    "endure",
    "enforce",
    "engineer",
    "enhance",
    "enjoy ",
    "enlist",
    "ensure",
    "enter ",
    "entertain",
    "escape ",
    "establish",
    "estimate",
    "evaluate",
    "examine",
    "exceed",
    "excite ",
    "excuse ",
    "execute",
    "exercise ",
    "exhibit",
    "exist ",
    "expand ",
    "expect",
    "expedite",
    "experiment",
    "explain ",
    "explode ",
    "express",
    "extend",
    "extract",
    "face ",
    "facilitate",
    "fade ",
    "fail ",
    "fancy ",
    "fasten ",
    "fax ",
    "fear ",
    "feed",
    "feel",
    "fence",
    "fetch ",
    "fight",
    "file ",
    "fill ",
    "film ",
    "finalize",
    "finance",
    "find",
    "fire ",
    "fit",
    "fix ",
    "flap",
    "flash ",
    "flee",
    "fling",
    "float ",
    "flood ",
    "flow ",
    "flower ",
    "fly",
    "fold ",
    "follow ",
    "fool",
    "forbid",
    "force ",
    "forecast",
    "forego ",
    "foresee",
    "foretell",
    "forget",
    "forgive",
    "form ",
    "formulate",
    "forsake",
    "frame ",
    "freeze",
    "frighten ",
    "fry",
    "gather ",
    "gaze ",
    "generate",
    "get",
    "give",
    "glow ",
    "glue",
    "go",
    "govern",
    "grab ",
    "graduate",
    "grate ",
    "grease ",
    "greet",
    "grin ",
    "grind",
    "grip ",
    "groan ",
    "grow",
    "guarantee",
    "guard ",
    "guess ",
    "guide",
    "hammer ",
    "hand ",
    "handle ",
    "handwrite",
    "hang",
    "happen ",
    "harass",
    "harm ",
    "hate ",
    "haunt ",
    "head ",
    "heal ",
    "heap",
    "hear",
    "heat ",
    "help ",
    "hide",
    "hit",
    "hold",
    "hook ",
    "hop ",
    "hope ",
    "hover",
    "hug ",
    "hum ",
    "hunt ",
    "hurry",
    "hurt",
    "hypothesize",
    "identify ",
    "ignore ",
    "illustrate",
    "imagine ",
    "implement",
    "impress ",
    "improve ",
    "improvise",
    "include",
    "increase ",
    "induce",
    "influence ",
    "inform ",
    "initiate",
    "inject ",
    "injure ",
    "inlay",
    "innovate",
    "input",
    "inspect",
    "inspire",
    "install",
    "institute",
    "instruct",
    "insure",
    "integrate",
    "intend ",
    "intensify",
    "interest ",
    "interfere ",
    "interlay",
    "interpret",
    "interrupt ",
    "interview",
    "introduce ",
    "invent",
    "inventory",
    "investigate",
    "invite ",
    "irritate ",
    "itch",
    "jail ",
    "jam",
    "jog ",
    "join",
    "joke ",
    "judge",
    "juggle ",
    "jump",
    "justify",
    "keep",
    "kept ",
    "kick ",
    "kill",
    "kiss ",
    "kneel",
    "knit ",
    "knock",
    "knot",
    "know",
    "label ",
    "land ",
    "last ",
    "laugh ",
    "launch",
    "lay",
    "lead",
    "lean",
    "leap",
    "learn",
    "leave",
    "lecture",
    "led",
    "lend",
    "let",
    "level ",
    "license ",
    "lick ",
    "lie",
    "lifted",
    "light",
    "lighten ",
    "like ",
    "list ",
    "listen ",
    "live",
    "load ",
    "locate",
    "lock ",
    "log",
    "long ",
    "look ",
    "lose",
    "love",
    "maintain",
    "make",
    "man ",
    "manage ",
    "manipulate",
    "manufacture",
    "map",
    "march ",
    "mark ",
    "market",
    "marry ",
    "match ",
    "mate",
    "matter ",
    "mean",
    "measure ",
    "meddle ",
    "mediate",
    "meet",
    "melt",
    "melt ",
    "memorize",
    "mend ",
    "mentor",
    "milk ",
    "mine ",
    "mislead",
    "miss ",
    "misspell",
    "mistake",
    "misunderstand",
    "mix ",
    "moan ",
    "model",
    "modify",
    "monitor",
    "moor ",
    "motivate",
    "mourn",
    "move ",
    "mow",
    "muddle ",
    "mug ",
    "multiply ",
    "murder",
    "nail ",
    "name",
    "navigate",
    "need ",
    "negotiate",
    "nest",
    "nod ",
    "nominate",
    "normalize",
    "note",
    "notice ",
    "number",
    "obey ",
    "object ",
    "observe",
    "obtain ",
    "occur ",
    "offend",
    "offer ",
    "officiate",
    "open ",
    "operate",
    "order",
    "organize",
    "oriented",
    "originate",
    "overcome",
    "overdo",
    "overdraw",
    "overflow ",
    "overhear",
    "overtake",
    "overthrow",
    "owe ",
    "own",
    "pack ",
    "paddle ",
    "paint ",
    "park ",
    "part ",
    "participate",
    "pass ",
    "paste ",
    "pat ",
    "pause ",
    "pay",
    "peck ",
    "pedal ",
    "peel ",
    "peep ",
    "perceive",
    "perfect",
    "perform",
    "permit ",
    "persuade",
    "phone ",
    "photograph",
    "pick ",
    "pilot",
    "pinch ",
    "pine ",
    "pinpoint",
    "pioneer",
    "place ",
    "plan ",
    "plant ",
    "play ",
    "plead",
    "please ",
    "plug ",
    "point ",
    "poke ",
    "polish",
    "pop ",
    "possess ",
    "post ",
    "pour ",
    "practice ",
    "praised",
    "pray ",
    "preach ",
    "precede ",
    "predict",
    "prefer ",
    "prepare ",
    "prescribe",
    "present ",
    "preserve ",
    "preset",
    "preside",
    "press ",
    "pretend",
    "prevent ",
    "prick ",
    "print ",
    "process",
    "procure",
    "produce ",
    "profess",
    "program ",
    "progress",
    "project",
    "promise ",
    "promote",
    "proofread",
    "propose",
    "protect ",
    "prove",
    "provide ",
    "publicize",
    "pull ",
    "pump ",
    "punch ",
    "puncture ",
    "punish ",
    "purchase",
    "push",
    "put",
    "qualify",
    "question",
    "queue",
    "quit",
    "race ",
    "radiate ",
    "rain ",
    "raise ",
    "rank",
    "rate",
    "reach ",
    "read",
    "realign",
    "realize ",
    "reason",
    "receive ",
    "recognize ",
    "recommend",
    "reconcile",
    "record ",
    "recruit",
    "reduce ",
    "refer",
    "reflect",
    "refuse ",
    "regret ",
    "regulate",
    "rehabilitate",
    "reign ",
    "reinforce",
    "reject ",
    "rejoice ",
    "relate",
    "relax ",
    "release ",
    "rely ",
    "remain ",
    "remember ",
    "remind",
    "remove ",
    "render",
    "reorganize",
    "repair ",
    "repeat ",
    "replace ",
    "reply ",
    "report ",
    "represent",
    "reproduce ",
    "request ",
    "rescue ",
    "research",
    "resolve",
    "respond",
    "restored",
    "restructure",
    "retire ",
    "retrieve",
    "return",
    "review",
    "revise",
    "rhyme ",
    "rid",
    "ride",
    "ring",
    "rinse ",
    "rise",
    "risk ",
    "rob ",
    "rock ",
    "roll ",
    "rot ",
    "rub ",
    "ruin ",
    "rule ",
    "run",
    "rush",
    "sack ",
    "sail ",
    "satisfy ",
    "save ",
    "saw",
    "say",
    "scare ",
    "scatter ",
    "schedule",
    "scold ",
    "scorch ",
    "scrape ",
    "scratch ",
    "scream ",
    "screw ",
    "scribble ",
    "scrub ",
    "seal ",
    "search ",
    "secure",
    "see",
    "seek",
    "select",
    "sell",
    "send",
    "sense",
    "separate ",
    "serve ",
    "service",
    "set",
    "settle ",
    "sew",
    "shade ",
    "shake",
    "shape",
    "share ",
    "shave",
    "shear",
    "shed",
    "shelter",
    "shine",
    "shiver ",
    "shock ",
    "shoe",
    "shoot",
    "shop ",
    "show",
    "shrink",
    "shrug ",
    "shut",
    "sigh ",
    "sign ",
    "signal ",
    "simplify",
    "sin ",
    "sing",
    "sink",
    "sip ",
    "sit",
    "sketch",
    "ski ",
    "skip ",
    "slap ",
    "slay",
    "sleep",
    "slide",
    "sling",
    "slink",
    "slip ",
    "slit",
    "slow ",
    "smash ",
    "smell",
    "smile ",
    "smite",
    "smoke ",
    "snatch ",
    "sneak",
    "sneeze ",
    "sniff ",
    "snore ",
    "snow ",
    "soak",
    "solve",
    "soothe ",
    "soothsay",
    "sort",
    "sound ",
    "sow",
    "spare ",
    "spark ",
    "sparkle ",
    "speak",
    "specify",
    "speed",
    "spell ",
    "spend",
    "spill",
    "spin",
    "spit",
    "split",
    "spoil",
    "spot ",
    "spray ",
    "spread",
    "spring",
    "sprout ",
    "squash ",
    "squeak ",
    "squeal ",
    "squeeze ",
    "stain ",
    "stamp ",
    "stand",
    "stare ",
    "start ",
    "stay ",
    "steal",
    "steer ",
    "step ",
    "stick",
    "stimulate",
    "sting",
    "stink",
    "stir ",
    "stitch",
    "stop ",
    "store ",
    "strap ",
    "streamline",
    "strengthen ",
    "stretch ",
    "stride",
    "strike",
    "string",
    "strip",
    "strive",
    "stroke ",
    "structure",
    "study",
    "stuff ",
    "sublet",
    "subtract ",
    "succeed ",
    "suck ",
    "suffer ",
    "suggest ",
    "suit ",
    "summarize",
    "supervise",
    "supply ",
    "support ",
    "suppose ",
    "surprise ",
    "surround ",
    "suspect ",
    "suspend ",
    "swear",
    "sweat",
    "sweep",
    "swell",
    "swim",
    "swing",
    "switch",
    "symbolize",
    "synthesize",
    "systemize",
    "tabulate",
    "take",
    "talk ",
    "tame ",
    "tap ",
    "target",
    "taste ",
    "teach",
    "tear",
    "tease ",
    "telephone ",
    "tell",
    "tempt ",
    "terrify ",
    "test ",
    "thank",
    "thaw ",
    "think",
    "thrive",
    "throw",
    "thrust",
    "tick ",
    "tickle ",
    "tie ",
    "time ",
    "tip ",
    "tire ",
    "touch ",
    "tour ",
    "tow",
    "trace ",
    "trade ",
    "train ",
    "transcribe",
    "transfer",
    "transform",
    "translate",
    "transport ",
    "trap ",
    "travel ",
    "tread",
    "treat ",
    "tremble ",
    "trick ",
    "trip",
    "trot ",
    "trouble ",
    "troubleshoot",
    "trust ",
    "try ",
    "tug ",
    "tumble ",
    "turn ",
    "tutor",
    "twist ",
    "type",
    "undergo",
    "understand",
    "undertake",
    "undress ",
    "unfasten",
    "unify",
    "unite",
    "unlock",
    "unpack ",
    "untidy",
    "update",
    "upgrade",
    "uphold",
    "upset",
    "use",
    "utilize",
    "vanish",
    "verbalize",
    "verify",
    "vex",
    "visit",
    "wail ",
    "wait ",
    "wake",
    "walk ",
    "wander ",
    "want ",
    "warm ",
    "warn ",
    "wash",
    "waste ",
    "watch ",
    "water ",
    "wave ",
    "wear",
    "weave",
    "wed",
    "weep",
    "weigh ",
    "welcome ",
    "wend",
    "wet",
    "whine ",
    "whip",
    "whirl ",
    "whisper ",
    "whistle ",
    "win",
    "wind",
    "wink ",
    "wipe ",
    "wish ",
    "withdraw",
    "withhold",
    "withstand",
    "wobble ",
    "wonder",
    "work ",
    "worry ",
    "wrap ",
    "wreck ",
    "wrestle ",
    "wriggle",
    "wring",
    "write",
    "x-ray",
    "yawn",
    "yell",
    "zip",
    "zoom"
];

//endregion words lists

jsrpg.random.adjective = function() {
    return jsrpg.random._arrayAdjectives[Math.random() * jsrpg.random._arrayAdjectives.length];
};

jsrpg.random.noun = function() {
    return jsrpg.random._arrayNouns[Math.random() * jsrpg.random._arrayNouns.length];
};

jsrpg.random.verb = function() {
    return jsrpg.random._arrayVerbs[Math.random() * jsrpg.random._arrayVerbs.length];
};